<a href="https://colab.research.google.com/github/Deeksha040/Statistics/blob/main/MatrixVectorBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numeric vectors
n1 <- 20
n2 <- c(20, 25, 60, 55)

In [ ]:
# Character vectors
c1 <- "Blue"
c2 <- c("Red", "Green", "Purple")

In [ ]:
# Logical vectors
l1 <- TRUE
l2 <- c(TRUE, FALSE, TRUE)

In [ ]:
n1 <- seq(from = 0, to = 10, by = 2)   #using 'by'
n1

[1]  0  2  4  6  8 10

In [ ]:
n2 <- seq(from = 0, to = 10, length.out = 5)   #using 'length.out'
n2

[1]  0.0  2.5  5.0  7.5 10.0

In [ ]:
n3 <- seq(1, 2, 0.1)   #no argument names specified; automatically uses 'from', 'to', 'by'
n3

[1] 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0

In [ ]:
n4 <- 1:5    #shortcut for integer sequence; same as 'seq(1, 5, 1)'
n4

[1] 1 2 3 4 5

In [ ]:
rep(1, 5)

[1] 1 1 1 1 1

In [ ]:
rep("blue", 3)

[1] "blue" "blue" "blue"

In [ ]:
rep(TRUE, 4)

[1] TRUE TRUE TRUE TRUE

In [ ]:
rep(c("blue", "red"), 3)

[1] "blue" "red"  "blue" "red"  "blue" "red"

In [ ]:
c(rep(seq(0, 6, 2), 2), 4:1)

[1] 0 2 4 6 0 2 4 6 4 3 2 1

In [ ]:
fruits <- c("apple", "banana")
fruits[c(TRUE, FALSE)]

[1] "apple"

In [ ]:
# Create a vector with 30 fruits
fruits <- rep(c("orange", "apple", "banana"), 10)
fruits

[1] "orange" "apple"  "banana" "orange" "apple"  "banana" "orange" "apple" 
 [9] "banana" "orange" "apple"  "banana" "orange" "apple"  "banana" "orange"
[17] "apple"  "banana" "orange" "apple"  "banana" "orange" "apple"  "banana"
[25] "orange" "apple"  "banana" "orange" "apple"  "banana"

In [ ]:
# Create a logical vector for dropping bananas
# Note: I'm creating the exact same logical vector three times (overriding it each time)
# This is for illustrative purposes; using one of these is sufficient
lv <- fruits == "orange" | fruits == "apple"
lv <- fruits != "banana"
lv <- fruits %in% c("orange", "apple")
lv

[1]  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE
[13]  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE
[25]  TRUE  TRUE FALSE  TRUE  TRUE FALSE

In [ ]:
# Carry out the subset
fruits[lv]

[1] "orange" "apple"  "orange" "apple"  "orange" "apple"  "orange" "apple" 
 [9] "orange" "apple"  "orange" "apple"  "orange" "apple"  "orange" "apple" 
[17] "orange" "apple"  "orange" "apple"

In [ ]:
# Create a numeric vector
numbers <- seq(0, 100, by = 10)
numbers

[1]   0  10  20  30  40  50  60  70  80  90 100

In [ ]:
# Illustrate three different filters
numbers[numbers <= 50 & numbers != 30]

[1]  0 10 20 40 50

In [ ]:
numbers[numbers == 0 | numbers == 100]

[1]   0 100

In [ ]:
numbers[numbers > 100] #returns an empty vector

numeric(0)

In [ ]:
# Subsetting using indexing
fruits <- c("apple", "banana")
fruits[1]

[1] "apple"

In [ ]:
fruits <- rep(c("orange", "apple", "banana"), 10)
fruits[c(10, 20)]

[1] "orange" "apple"

In [ ]:
fruits[seq(1, 30, by = 5)]

[1] "orange" "banana" "apple"  "orange" "banana" "apple"

In [ ]:
# Draw 10 elements at random from 1 to 100
sample(1:100, size = 10)

[1] 80 68 86 47 15 73 83 13 36 62

In [ ]:
fruits <- rep(c("orange", "apple", "banana"), 10)
fruits[sample(1:30, size = 5)]

[1] "orange" "apple"  "orange" "banana" "apple"

In [ ]:
# Subsetting using names
age <- c(50, 55, 80)
names(age) <- c("mom", "dad", "grandpa")
age #note that values now have names

mom     dad grandpa 
     50      55      80

In [ ]:
age[c("dad", "grandpa")]

dad grandpa 
     55      80

In [ ]:
# Modifying vectors
# Recreate vector with age values from above
age <- c(50, 55, 80)
names(age) <- c("mom", "dad", "grandpa")

# Three ways of changing grandpa's age
# Note: you'd only need to use one of these
age[age == 80] <- 82 #using a logical statement
age[3] <- 82 #using indexing
age["grandpa"] <- 82 #using naming
age

mom     dad grandpa 
     50      55      82

In [ ]:
fruits <- rep(c("orange", "apple", "bamama"), 5)
fruits #bamamas anyone?

[1] "orange" "apple"  "bamama" "orange" "apple"  "bamama" "orange" "apple" 
 [9] "bamama" "orange" "apple"  "bamama" "orange" "apple"  "bamama"

In [ ]:
# Let's fix the misspelled element
fruits[fruits == "bamama"] <- "banana"
fruits

[1] "orange" "apple"  "banana" "orange" "apple"  "banana" "orange" "apple" 
 [9] "banana" "orange" "apple"  "banana" "orange" "apple"  "banana"

In [ ]:
# Vector arithmetics
numbers <- 1:10
numbers

[1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
# One value modifying all values in a vector
numbers <- numbers / 10
numbers

[1] 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0

In [ ]:
# One value modifying a subset of a vector
numbers[numbers > 0.5] <- numbers[numbers > 0.5] * 100
numbers

[1]   0.1   0.2   0.3   0.4   0.5  60.0  70.0  80.0  90.0 100.0

In [ ]:
# Two vectors with the same number of elements
numbers1 <- 1:10
numbers2 <- 10:1
numbers3 <- numbers2 - numbers1
numbers3

[1]  9  7  5  3  1 -1 -3 -5 -7 -9

In [ ]:
# Replacing a subset of a vector using another vector
numbers <- 1:10
numbers[numbers > 5] <- 5:1
numbers

[1] 1 2 3 4 5 5 4 3 2 1

In [ ]:
# Modify a vector (or a subset of a vector) using a function
numbers <- 1:10
sqrt(numbers) #square root

[1] 1.000000 1.414214 1.732051 2.000000 2.236068 2.449490 2.645751 2.828427
 [9] 3.000000 3.162278

In [ ]:
exp(numbers) #exponentiate

[1]     2.718282     7.389056    20.085537    54.598150   148.413159
 [6]   403.428793  1096.633158  2980.957987  8103.083928 22026.465795

In [ ]:
log(numbers[c(1, 5, 10)]) #natural log

[1] 0.000000 1.609438 2.302585

In [ ]:
# Summarizing vectors
numbers <- sample(1:1000, 10)
numbers

[1] 666 611 489 255 232 637 560 301 145 574

In [ ]:
class(numbers) #check the class

[1] "integer"

In [ ]:
numbers <- sample(1:1000, 10)
numbers

[1] 145

In [ ]:
length(numbers) #number of elements

max(numbers) #maximum value

min(numbers) #minimum value

sum(numbers) #sum of all values in the vector

mean(numbers) #mean

median(numbers) #median

var(numbers) #variance

sd(numbers) #standard deviation

quantile(numbers) #percentiles in intervals of .25

quantile(numbers, probs = seq(0, 1, 0.1)) #percentiles in invervals of 0.1

summary(numbers)

[1] 10

[1] 666

[1] 145

[1] 4470

[1] 447

[1] 524.5

[1] 37469.78

[1] 193.5711

0%    25%    50%    75%   100% 
145.00 266.50 524.50 601.75 666.00

0%   10%   20%   30%   40%   50%   60%   70%   80%   90%  100% 
145.0 223.3 250.4 287.2 413.8 524.5 565.6 585.1 616.2 639.9 666.0

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  145.0   266.5   524.5   447.0   601.8   666.0 

In [ ]:
 A = matrix(
     c(2, 4, 3, 1, 5, 7), # the data elements
     nrow=2,              # number of rows
     ncol=3,              # number of columns
     byrow = TRUE)        # fill matrix by rows
A

[,1] [,2] [,3]
[1,] 2    4    3   
[2,] 1    5    7

In [ ]:
A[2, 3]

[1] 7

In [ ]:
A[2, ]

[1] 1 5 7

In [ ]:
A[ ,3]

[1] 3 7

In [ ]:
A[ ,c(1,3)]  # the 1st and 3rd columns

[,1] [,2]
[1,] 2    3   
[2,] 1    7

In [ ]:
 dimnames(A) = list(
     c("row1", "row2"),         # row names
     c("col1", "col2", "col3")) # column names
A

col1 col2 col3
row1 2    4    3   
row2 1    5    7

In [ ]:
A["row2", "col3"] # element at 2nd row, 3rd column

[1] 7

In [ ]:
 B = matrix(
     c(2, 4, 3, 1, 5, 7),
     nrow=3,
     ncol=2)
B

[,1] [,2]
[1,] 2    1   
[2,] 4    5   
[3,] 3    7

In [ ]:
 t(B)          # transpose of B

[,1] [,2] [,3]
[1,] 2    4    3   
[2,] 1    5    7

In [ ]:
# Combining Matrices
C = matrix(
    c(7, 4, 2),
    nrow=3,
    ncol=1)
C

[,1]
[1,] 7   
[2,] 4   
[3,] 2

In [ ]:
cbind(B, C)

[,1] [,2] [,3]
[1,] 2    1    7   
[2,] 4    5    4   
[3,] 3    7    2

In [ ]:
D = matrix(
    c(6, 2),
    nrow=1,
    ncol=2)
D

[,1] [,2]
[1,] 6    2

In [ ]:
rbind(B, D)

[,1] [,2]
[1,] 2    1   
[2,] 4    5   
[3,] 3    7   
[4,] 6    2

In [ ]:
# Matrix deconstruction
c(B)

[1] 2 4 3 1 5 7